//auth
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const FORGOT_PASS_SUCCESS = "FORGOT_PASS_SUCCESS";
export const FORGOT_PASS_FAIL = "FORGOT_PASS_FAIL";
export const RESET_PASS_SUCCESS = "RESET_PASS_SUCCESS";
export const RESET_PASS_FAIL = "RESET_PASS_FAIL";
export const CHANGE_PASS_SUCCESS = "CHANGE_PASS_SUCCESS";
export const CHANGE_PASS_FAIL = "CHANGE_PASS_FAIL";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";
export const AFTER_UPDATE_USER_SUCCESS = "AFTER_UPDATE_USER_SUCCESS";
export const DISABLE_USER_SUCCESS = "DISABLE_USER_SUCCESS";
export const DISABLE_USER_FAIL = "DISABLE_USER_FAIL";
//fitness details
export const GET_LATEST_FITNESS_DETAILS_LOADING =
  "GET_LATEST_FITNESS_DETAILS_LOADING";
export const GET_LATEST_FITNESS_DETAILS_SUCCESS =
  "GET_LATEST_FITNESS_DETAILS_SUCCESS";
export const GET_LATEST_FITNESS_DETAILS_FAIL =
  "GET_LATEST_FITNESS_DETAILS_FAIL";
export const GET_ALL_FITNESS_DETAILS_LOADING =
  "GET_ALL_FITNESS_DETAILS_LOADING";
export const GET_ALL_FITNESS_DETAILS_SUCCESS =
  "GET_ALL_FITNESS_DETAILS_SUCCESS";
export const GET_ALL_FITNESS_DETAILS_FAIL = "GET_ALL_FITNESS_DETAILS_FAIL";
export const ADD_FITNESS_DETAILS_SUCCESS = "ADD_FITNESS_DETAILS_SUCCESS";
export const ADD_FITNESS_DETAILS_FAIL = "ADD_FITNESS_DETAILS_FAIL";
export const UPDATE_FITNESS_DETAILS_SUCCESS = "UPDATE_FITNESS_DETAILS_SUCCESS";
export const UPDATE_FITNESS_DETAILS_FAIL = "UPDATE_FITNESS_DETAILS_FAIL";
//user's objectives
export const GET_CURRENT_OBJECTIVE_LOADING = "GET_CURRENT_OBJECTIVE_LOADING";
export const GET_CURRENT_OBJECTIVE_SUCCESS = "GET_CURRENT_OBJECTIVE_SUCCESS";
export const GET_CURRENT_OBJECTIVE_FAIL = "GET_CURRENT_OBJECTIVE_FAIL";
export const GET_OBJECTIVES_HISTORY_LOADING = "GET_OBJECTIVES_HISTORY_LOADING";
export const GET_OBJECTIVES_HISTORY_SUCCESS = "GET_OBJECTIVES_HISTORY_SUCCESS";
export const GET_OBJECTIVES_HISTORY_FAIL = "GET_OBJECTIVES_HISTORY_FAIL";
export const ADD_OBJECTIVE_SUCCESS = "ADD_OBJECTIVE_SUCCESS";
export const ADD_OBJECTIVE_FAIL = "ADD_OBJECTIVE_FAIL";
export const UPDATE_CURRENT_OBJECTIVE_SUCCESS =
  "UPDATE_CURRENT_OBJECTIVE_SUCCESS";
export const UPDATE_CURRENT_OBJECTIVE_FAIL = "UPDATE_CURRENT_OBJECTIVE_FAIL";
//errors
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
//foods
export const GET_FOODS_BY_TYPE_LOADING = "GET_FOODS_BY_TYPE_LOADING";
export const GET_FOODS_BY_TYPE_SUCCESS = "GET_FOODS_BY_TYPE_SUCCESS";
export const GET_FOODS_BY_TYPE_FAIL = "GET_FOODS_BY_TYPE_FAIL";
export const GET_FOOD_DETAILS_LOADING = "GET_FOOD_DETAILS_LOADING";
export const GET_FOOD_DETAILS_SUCCESS = "GET_FOOD_DETAILS_SUCCESS";
export const GET_FOOD_DETAILS_FAIL = "GET_FOOD_DETAILS_FAIL";
export const CLEAR = "CLEAR";
//user's foods
export const ADD_USER_FOOD_SUCCESS = "ADD_USER_FOOD_SUCCESS";
export const ADD_USER_FOOD_FAIL = "ADD_USER_FOOD_FAIL";
export const AFTER_ADD_USER_FOOD_SUCCESS = "AFTER_ADD_USER_FOOD_SUCCESS";
export const SAVE_USER_FOOD_SUCCESS = "SAVE_USER_FOOD_SUCCESS";
export const SAVE_USER_FOOD_FAIL = "SAVE_USER_FOOD_FAIL";
export const AFTER_SAVE_USER_FOOD_SUCCESS = "AFTER_SAVE_USER_FOOD_SUCCESS";
export const DELETE_USER_FOOD_SUCCESS = "DELETE_USER_FOOD_SUCCESS";
export const DELETE_USER_FOOD_FAIL = "DELETE_USER_FOOD_FAIL";
export const GET_USER_FOODS_LOADING = "GET_ALL_USER_FOODS_LOADING";
export const GET_USER_FOODS_SUCCESS = "GET_ALL_USER_FOODS_SUCCESS";
export const GET_USER_FOODS_FAIL = "GET_ALL_USER_FOODS_FAIL";
//exercises
export const GET_EXERCISES_BY_TYPE_LOADING = "GET_EXERCISES_BY_TYPE_LOADING";
export const GET_EXERCISES_BY_TYPE_SUCCESS = "GET_EXERCISES_BY_TYPE_SUCCESS";
export const GET_EXERCISES_BY_TYPE_FAIL = "GET_EXERCISES_BY_TYPE_FAIL";
export const GET_EXERCISE_DETAILS_LOADING = "GET_EXERCISE_DETAILS_LOADING";
export const GET_EXERCISE_DETAILS_SUCCESS = "GET_EXERCISE_DETAILS_SUCCESS";
export const GET_EXERCISE_DETAILS_FAIL = "GET_EXERCISE_DETAILS_FAIL";
//user's exercises
export const ADD_USER_EXERCISE_SUCCESS = "ADD_USER_EXERCISE_SUCCESS";
export const ADD_USER_EXERCISE_FAIL = "ADD_USER_EXERCISE_FAIL";
export const AFTER_ADD_USER_EXERCISE_SUCCESS =
  "AFTER_ADD_USER_EXERCISE_SUCCESS";
export const SAVE_USER_EXERCISE_SUCCESS = "SAVE_USER_EXERCISE_SUCCESS";
export const SAVE_USER_EXERCISE_FAIL = "SAVE_USER_EXERCISE_FAIL";
export const AFTER_SAVE_USER_EXERCISE_SUCCESS =
  "AFTER_SAVE_USER_EXERCISE_SUCCESS";
export const DELETE_USER_EXERCISE_SUCCESS = "DELETE_USER_EXERCISE_SUCCESS";
export const DELETE_USER_EXERCISE_FAIL = "DELETE_USER_EXERCISE_FAIL";
export const GET_USER_EXERCISES_LOADING = "GET_USER_EXERCISES_LOADING";
export const GET_USER_EXERCISES_SUCCESS = "GET_USER_EXERCISES_SUCCESS";
export const GET_USER_EXERCISES_FAIL = "GET_USER_EXERCISES_FAIL";
//supplements
export const GET_SUPPLEMENTS_BY_TYPE_LOADING =
  "GET_SUPPLEMENTS_BY_TYPE_LOADING";
export const GET_SUPPLEMENTS_BY_TYPE_SUCCESS =
  "GET_SUPPLEMENTS_BY_TYPE_SUCCESS";
export const GET_SUPPLEMENTS_BY_TYPE_FAIL = "GET_SUPPLEMENTS_BY_TYPE_FAIL";
export const GET_SUPPLEMENT_DETAILS_LOADING = "GET_SUPPLEMENT_DETAILS_LOADING";
export const GET_SUPPLEMENT_DETAILS_SUCCESS = "GET_SUPPLEMENT_DETAILS_SUCCESS";
export const GET_SUPPLEMENT_DETAILS_FAIL = "GET_SUPPLEMENT_DETAILS_FAIL";
//user's supplements
export const ADD_USER_SUPPLEMENT_SUCCESS = "ADD_USER_SUPPLEMENT_SUCCESS";
export const ADD_USER_SUPPLEMENT_FAIL = "ADD_USER_SUPPLEMENT_FAIL";
export const AFTER_ADD_USER_SUPPLEMENT_SUCCESS =
  "AFTER_ADD_USER_SUPPLEMENT_SUCCESS";
export const SAVE_USER_SUPPLEMENT_SUCCESS = "SAVE_USER_SUPPLEMENT_SUCCESS";
export const SAVE_USER_SUPPLEMENT_FAIL = "SAVE_USER_SUPPLEMENT_FAIL";
export const AFTER_SAVE_USER_SUPPLEMENT_SUCCESS =
  "AFTER_SAVE_USER_SUPPLEMENT_SUCCESS";
export const DELETE_USER_SUPPLEMENT_SUCCESS = "DELETE_USER_SUPPLEMENT_SUCCESS";
export const DELETE_USER_SUPPLEMENT_FAIL = "DELETE_USER_SUPPLEMENT_FAIL";
export const GET_USER_SUPPLEMENTS_LOADING = "GET_USER_SUPPLEMENTS_LOADING";
export const GET_USER_SUPPLEMENTS_SUCCESS = "GET_USER_SUPPLEMENTS_SUCCESS";
export const GET_USER_SUPPLEMENTS_FAIL = "GET_USER_SUPPLEMENTS_FAIL";
// chat
export const ADD_MESSAGE_LOADING = "ADD_MESSAGE_LOADING";
export const ADD_MESSAGE_SUCCESS = "ADD_MESSAGE_SUCCESS";
export const ADD_MESSAGE_FAIL = "ADD_MESSAGE_FAIL";
export const ADD_RESPONSE_LOADING = "ADD_RESPONSE_LOADING";
export const ADD_RESPONSE_SUCCESS = "ADD_RESPONSE_SUCCESS";
export const ADD_RESPONSE_FAIL = "ADD_RESPONSE_FAIL";
//context
export const SAVE_CONTEXT_LOADING = "SAVE_CONTEXT_LOADING";
export const SAVE_CONTEXT_SUCCESS = "SAVE_CONTEXT_SUCCESS";
export const SAVE_CONTEXT_FAIL = "SAVE_CONTEXT_FAIL";
